# Generated by Django 4.0 on 2021-12-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_user_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
    ]
